POST http://localhost:8080/api/login 
Content-Type: application/json

{
    "email" : "test@seznam.cz",
    "password" : "1234567"
}


###
GET http://localhost:8080/api/user/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAc2V6bmFtLmN6IiwiaWF0IjoxNjcwNjk3NjA3fQ.YB5gWO7w_u5sZgyerDRhoY5RA0tFeOJNI-q-SSK6BTw
Content-Type: application/json
